Repository AY2425S1-CS2103T-T09-2/tp, pull requests merged in 2024-11, with the labels that each got.

#123 Fix: DesiredRole field regex updated to allow spaces (#114)
  src/main/java/seedu/address/model/person/DesiredRole.java
Labels: type.Task, severity.Medium, alpha-bug

#135 Fix duplicate help button bug
  src/main/resources/view/MainWindowNew.fxml
Labels: priority.Medium, severity.VeryLow, alpha-bug

#136 Fix skills field to accept space, hashtag and colon
  src/main/java/seedu/address/model/person/Skills.java
  src/test/java/seedu/address/model/person/SkillsTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#141 Remove Note Command and its Test cases
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: type.Task, priority.High

#140 Update User Guide
  docs/UserGuide.md
  docs/images/LOGO.jpg
  docs/images/afteradd.png
  docs/images/afterclear.png
  docs/images/afterdelete.png
  docs/images/afteredit.png
  docs/images/afterfilter.png
  docs/images/afterfind.png
  docs/images/afterlist.png
  docs/images/beforeclear.png
  docs/images/beforedelete.png
  docs/images/beforeedit.png
  docs/images/beforefilter.png
  docs/images/beforefind.png
  docs/images/beforelist.png
  docs/images/exit.png
  docs/images/help.png
  docs/images/img_1.png
  docs/images/successimage.png
Labels: type.Task, priority.High

#144 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Enhancement, priority.Medium

#147 Updated the README and index
  README.md
  docs/index.md
Labels: type.Enhancement, priority.Medium

#148 fix tip no show bug
  docs/UserGuide.md
Labels: bug

#153 fix: Display error message for invalid status in filter command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FilterStatusCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterStatusCommandParserTest.java
Labels: bug, type.Task, type.Bug, priority.Medium

#150 Add summary command to help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug, severity.Low, alpha-bug

#158 Bug/fix edit command index
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: bug

#159 Bug fix: Resize result display and fix vertical scrollbar
  src/main/resources/view/NewTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug, alpha-bug

#160 Display Person Details with Labels in OverviewListCard
  src/main/java/seedu/address/ui/OverviewListCard.java
  src/main/resources/view/NewTheme.css
  src/main/resources/view/OverviewListCard.fxml
Labels: type.Bug, alpha-bug

#157 Update developer guide with TalentSG information
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/FilterStatusCommandSequenceDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/SummaryCommandSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/FilterStatusCommandSequenceDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/SummaryCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewCommandSequenceDiagram.png
Labels: documentation, priority.High

#161 Fix Report Bug color scheme doesn't match issue
  src/main/java/seedu/address/ui/MainWindowNew.java
  src/main/resources/images/report_icon.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindowNew.fxml
  src/main/resources/view/ReportBugWindow.fxml
Labels: type.Bug, alpha-bug

#163 Bug: View command does't recognise format or show error
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#162 Update OverviewListCard.fxml
  src/main/resources/view/OverviewListCard.fxml
Labels: type.Enhancement, priority.Medium

#166 Fix issues in developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MainWindowNew.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: documentation, type.Task, priority.High

#164 Bug fix for userGuide
  docs/UserGuide.md
  docs/images/afteradd.png
  docs/images/afterclear.png
  docs/images/afterdelete.png
  docs/images/afteredit.png
  docs/images/afterfilter.png
  docs/images/afterfind.png
  docs/images/afterlist.png
  docs/images/beforeclear.png
  docs/images/beforedelete.png
  docs/images/beforeedit.png
  docs/images/beforefilter.png
  docs/images/beforefind.png
  docs/images/beforelist.png
  docs/images/exit.png
  docs/images/help.png
  docs/images/successimage.png
Labels: documentation, type.Task, priority.High

#169 Bug/fix userguide assorted bug
  docs/UserGuide.md
  docs/images/aftersummary.png
  docs/images/afterview.png
  docs/images/beforesummary.png
  docs/images/beforeview.png
  docs/images/reportBugWindow.png
Labels: bug, priority.High

#170 fix bugs
  docs/UserGuide.md
Labels: bug

#171 fix userguide bugs
  docs/UserGuide.md
Labels: bug

#174 fix userguide bugs3
  docs/UserGuide.md
Labels: bug

#179 Fix scroll bar bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/NewTheme.css
  src/main/resources/view/OverviewPanel.fxml
Labels: type.Bug

#254 Add defensive coding
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterStatusCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/DesiredRole.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Experience.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Skills.java
  src/main/java/seedu/address/model/person/Status.java
Labels: type.Enhancement, severity.Low

#255 Change invalid status to valid status in sample command
  docs/UserGuide.md
Labels: documentation, severity.Low

#258 Fixed ALL Userguide bugs
  docs/UserGuide.md
Labels: bug, priority.High

#256 Added a known issue and bugs section, added a note about names in UG
  docs/UserGuide.md
Labels: type.Bug

#263 Update caution for edit command of duplicate
  docs/UserGuide.md
Labels: documentation, severity.VeryLow

#264 Update UG for some issues
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Skills.java
Labels: type.Bug, severity.Low

#272 fix all UG and DG bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: bug

#273 fix ug release
  docs/UserGuide.md
Labels: bug
